#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
mocap_node:
    ros__parameters:
        rigid_bodies:
            1:
                pose: "sam/mocap/pose"
                pose2d: "sam/mocap/pose_2d"
                odom: sam/mocap/odom
                tf: tf
                child_frame_id: "sam/base_link"
                parent_frame_id: "world"
            2:
                pose: "pool/pose"
                pose2d: "pool/ground_pose"
                odom: pool/Odom
                tf: tf
                child_frame_id: "pool/base_link"
                parent_frame_id: "world"
            3:
                pose: "nachos_magic_wand/pose"
                # pose2d: "pool/ground_pose"
                # odom: pool/Odom
                tf: tf
                child_frame_id: "nachos_magic_wand/base_link"
                parent_frame_id: "world"

        optitrack_config:
                multicast_address: "239.255.42.99"
                command_port: 1510
                data_port: 1511
                enable_optitrack: true
